---
title: Analysis of Bias Factors
output:
  word_document: 
    toc: true
    toc_depth: 3
  html_document:
    toc: true
    toc_depth: 3
---

```{r Setup, include=FALSE, warning=FALSE}
rm(list=ls())
library(dplyr)
library(tidyr)
library(broom)
library(tibble)
library(modelsummary)
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(viridis)
library(report)
library(car)
library(effectsize)
library(afex)
library(kableExtra)
load(file="/Users/xindieh/Documents/3_Academics/Projects/8_SelectionBias/simulation/simstudy/bias_factor_df.RData")
## auxiliary function
f_reg <- function(data=dfreg, parname="betaO1", trimpct=0) {
  res <- list()
  ## select interested parameter
  if (trimpct==0) {
    df <- data %>% dplyr::filter(parameter==parname)
  } else {
    ## remove outliers for each method
    df <- data %>% 
      dplyr::filter(parameter==parname) %>% 
      dplyr::group_by(method) %>% 
      dplyr::filter(AE<=quantile(AE, 1-trimpct)) %>% 
      dplyr::ungroup()
  } 
  ## overall regression
  fml_main <- AE ~ dependence+selectivity+x_dist+select_dist+outcome_dist
  fml_2nd <- AE ~ dependence+selectivity+I(dependence^2)+I(selectivity^2)+x_dist+select_dist+outcome_dist
  fml_int <- AE ~ dependence*selectivity+x_dist+select_dist+outcome_dist
  fml_all <- AE ~ dependence*selectivity+I(dependence^2)+I(selectivity^2)+x_dist+select_dist+outcome_dist
  res$overall <- df %>% 
    dplyr::filter(dependence >= 0 ) %>% 
    dplyr::group_by(method) %>% 
    dplyr::do(
      main_effect = lm(formula = fml_main, data = .),
      second_order = lm(formula = fml_2nd, data = .),
      interact_effect = lm(formula = fml_int, data = .), 
      all_effect = lm(formula = fml_all, data = .)
    ) %>% 
    arrange(desc(method))
  coef_map <-c("(Intercept)" = "(Intercept)", 
               "dependence" = "dependence",
               "I(dependence^2)" = "dependence^2", 
               "selectivity" = "selectivity", 
               "I(selectivity^2)" = "selectivity^2", 
               "dependence:selectivity" = "dependence*selectivity",
               "x_distUniform" = "X1 ~ uniform", 
               "x_distPoisson" = "X1 ~ poisson",
               "x_distNormal Mixture" = "X1 ~ normal mixture",
               "select_distProbit" = "selection ~ probit", 
               "outcome_distNormal" = "outcome ~ normal",
               "outcome_distPoisson" = "outcome ~ poisson",
               "outcome_distProbit" = "outcome ~ probit"
               )
  if (grepl(x=parname, pattern="betaS")) {
    rows <- tribble(~term, ~main_effect, ~second_order, ~interact_effect, ~all_effect,
                  ~main_effect, ~second_order, ~interact_effect, ~all_effect,
                  "X1 ~ normal", "-", "-", "-", "-", "-", "-", "-", "-", 
                  "selection ~ logit", "-", "-", "-", "-", "-", "-", "-", "-", 
                  "outcome ~ logit", "-", "-", "-", "-", "-", "-", "-", "-") 
    cnames2 <- res$overall$method
  } else {
    rows <- tribble(~term, ~main_effect, ~second_order, ~interact_effect, ~all_effect,
                  ~main_effect, ~second_order, ~interact_effect, ~all_effect,
                  ~main_effect, ~second_order, ~interact_effect, ~all_effect,
                  "X1 ~ normal", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-",
                  "selection ~ logit", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-",
                  "outcome ~ logit", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-") 
    cnames2 <- res$overall$method
  }
  attr(rows, "position") <- c(13, 20, 23)
  main <- paste0("DV : Absolute Error of ", parname, ", sample trimmed off ", trimpct*100, "%")
  res$overall_tab <- modelsummary(
    models = list(
      "Main Effects" = res$overall$main_effect %>% setNames(cnames2), 
      "2nd Order Effects" = res$overall$second_order %>% setNames(cnames2),
      "Interaction Effects" = res$overall$interact_effect %>% setNames(cnames2),
      "Both Effects" = res$overall$all_effect %>% setNames(cnames2)
      ), 
    add_rows=rows, shape="cbind", stars=TRUE, coef_map=coef_map, title=main, output = "html"
    )
  
  return(res)
}

f_anova <- function(data=dfreg, parname="betaO1", trimpct=0) {
  
  ## select interested parameter
  if (trimpct==0) {
    df <- data %>% 
      dplyr::filter(parameter==parname)
  } else {
    ## remove outliers for each method
    df <- data %>% 
      dplyr::filter(parameter==parname) %>% 
      dplyr::group_by(method) %>% 
      dplyr::filter(AE<=quantile(AE, 1-trimpct)) %>% 
      dplyr::ungroup()
  } 
  ## anova
  df$id <- rownames(df)
  fml_aov <- AE ~ dependence*selectivity*x_dist + (1|id)
  res <- df %>% 
    dplyr::filter(dependence >= 0 ) %>% 
    dplyr::group_by(select_dist, outcome_dist) %>% 
    dplyr::do(
      anova = afex::aov_4(
        formula = fml_aov, data = ., type=3)
    )
  
  # Two-way plots: by select-outcome-method
  df$Dependence <- factor(abs(df$dependence), labels=c("zero","low","medium","high"))
  df$Selectivity <- factor(df$selectivity, labels=c("low visibility","medium visibility","high visibility"))
  df$Method <- factor(df$method, levels=c("OLS","Heckit","Copula")) %>% recode_factor("OLS"="None")
  df$X1_Distribution <- factor(df$x_dist, levels=c("Normal","Uniform","Poisson","Normal Mixture"))
  specs <- cbind(res$select_dist, res$outcome_dist)
  ## Dependence x Selectivity
  plots <- list()
  dfplot <- df %>%
    dplyr::group_by(select_dist, outcome_dist, Method, Dependence, Selectivity) %>%
    dplyr::summarise(MAE = mean(AE), SE = sd(AE)/sqrt(n()),
                     lb = MAE - 1.96*SE, ub = MAE + 1.96*SE)
  for (i in 1:nrow(specs)) {
    plots[[i]] <- ggplot(
      data = dplyr::filter(dfplot, select_dist==specs[i,1], outcome_dist==specs[i,2]),
      aes(x = Dependence, y = MAE, fill = Method)) + 
      facet_grid(cols=vars(Selectivity), scales="free") + 
      labs(x="Dependence", y=paste0("Absolute Error of ", parname), fill="Correction Method",
           title = paste0(specs[i,1],"-",specs[i,2], " : Dependence x Selectivity Interaction"),
           caption = paste0("(based on simulations trimmed off at ", 100*trimpct, "%)")) +
      geom_bar(stat = "identity", position = "dodge") +
      geom_errorbar(aes(x = Dependence, ymin = lb, ymax = ub),
                    color = "black", position = position_dodge(0.8), width = 0.2) +
      theme(legend.position = "top",
            panel.spacing=unit(1,"lines"),
            title = element_text(size=11,face="bold"),
            axis.title = element_text(size=11,face="bold"),
            axis.text = element_text(size=10),
            axis.text.x = element_text(angle=30, vjust =1, hjust=1),
            legend.title = element_text(size=10,face="bold"),
            legend.text = element_text(size=10),
            legend.key.size = unit(0.8, 'cm')
            ) + 
      scale_fill_manual(values=viridis(3)) 
  }
  res$plot_DS <- plots
  ## Dependence x X1 Distribution
  plots <- list()
  dfplot <- df %>%
    dplyr::group_by(select_dist, outcome_dist, Method, Dependence, X1_Distribution) %>%
    dplyr::summarise(MAE = mean(AE), SE = sd(AE)/sqrt(n()), 
                     lb = MAE - 1.96*SE, ub = MAE + 1.96*SE)
  for (i in 1:nrow(specs)) {
    plots[[i]] <- ggplot(
      data = dplyr::filter(dfplot, select_dist==specs[i,1], outcome_dist==specs[i,2]),
      aes(x = Dependence, y = MAE, fill = Method)) +
      facet_grid(cols=vars(X1_Distribution), scales="free") + 
      labs(x="Dependence", y=paste0("Absolute Error of ", parname), fill="Correction Method",
           title = paste0(specs[i,1],"-",specs[i,2], " : Dependence x X1_Distribution Interaction"),
           caption = paste0("(based on simulations trimmed off at ", 100*trimpct, "%)")) +
      geom_bar(stat = "identity", position = "dodge") +
      geom_errorbar(aes(x = Dependence, ymin = lb, ymax = ub),
                    color = "black", position = position_dodge(0.8), width = 0.2) +
      theme(legend.position = "none",
            panel.spacing=unit(1,"lines"),
            title = element_text(size=11,face="bold"),
            axis.title = element_text(size=11,face="bold"),
            axis.text = element_text(size=10),
            axis.text.x = element_text(angle=30, vjust =1, hjust=1),
            legend.title = element_text(size=10,face="bold"),
            legend.text = element_text(size=10),
            legend.key.size = unit(0.8, 'cm')
            ) + 
      scale_fill_manual(values=viridis(3))
  }
  res$plot_DX <- plots
  ## X1_Distribution x Selectivity
  plots <- list()
  dfplot <- df %>%
    dplyr::group_by(select_dist, outcome_dist, Method, Selectivity, X1_Distribution) %>%
    dplyr::summarise(MAE = mean(AE), SE = sd(AE)/sqrt(n()), 
                     lb = MAE - 1.96*SE, ub = MAE + 1.96*SE)
  for (i in 1:nrow(specs)) {
    plots[[i]] <- ggplot(
      data = dplyr::filter(dfplot, select_dist==specs[i,1], outcome_dist==specs[i,2]),
      aes(x = X1_Distribution, y = MAE, fill = Method)) +
      facet_grid(cols=vars(Selectivity), scales="free") + 
      labs(x="X1_Distribution", y=paste0("Absolute Error of ", parname), fill="Correction Method",
           title = paste0(specs[i,1],"-",specs[i,2], " : X1_Distribution x Selectivity Interaction"),
           caption = paste0("(based on simulations trimmed off at ", 100*trimpct, "%)")) +
      geom_bar(stat = "identity", position = "dodge") +
      geom_errorbar(aes(x = X1_Distribution, ymin = lb, ymax = ub),
                    color = "black", position = position_dodge(0.8), width = 0.2) + 
      theme(legend.position = "none",
            panel.spacing=unit(1,"lines"),
            title = element_text(size=11,face="bold"),
            axis.title = element_text(size=11,face="bold"),
            axis.text = element_text(size=10),
            axis.text.x = element_text(angle=30, vjust =1, hjust=1),
            legend.title = element_text(size=10,face="bold"),
            legend.text = element_text(size=10),
            legend.key.size = unit(0.8, 'cm')
            ) + 
      scale_fill_manual(values=viridis(3))
  }
  res$plot_XS <- plots
  
  return(res)
}

f_method <- function(data=dfreg, parname="betaO1", trimpct=0) {
  
  ## select interested parameter
  if (trimpct==0) {
    df <- data %>% 
      dplyr::filter(parameter==parname)
  } else {
    ## remove outliers for each method
    df <- data %>% 
      dplyr::filter(parameter==parname) %>% 
      dplyr::group_by(method) %>% 
      dplyr::filter(AE<=quantile(AE, 1-trimpct)) %>% 
      dplyr::ungroup()
  } 
  ## anova
  df$id <- rownames(df)
  fml_mtd <- AE ~ method + (1|id)
  res <- df %>% 
    dplyr::filter(dependence >= 0 ) %>% 
    dplyr::group_by(select_dist, outcome_dist) %>% 
    dplyr::do(
      anova = afex::aov_4(
        formula = fml_mtd, data = ., type=3)
    )
  
  return(res)
}

```

## Regression Tables

```{r OverallReg, eval=FALSE, warning=FALSE, results='asis'}
parnames <- c("betaO0", "betaO1", "betaO2", "betaS0", "betaS1", "betaS2", "betaS3")
res0 <- list()
for (i in 1:(length(parnames))) {
  res0[[i]] <- f_reg(data=dfreg, parname=parnames[[i]], trimpct=0.003)
}
```

<!-- ### betaO0 : intercept in outcome equation -->

<!-- ```{r Reg_bo0, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 1 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaO1 : coefficient on endogenous variable X1 -->

<!-- ```{r Reg_bo1, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 2 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaO2 : coefficient on exogenous variable X2 -->

<!-- ```{r Reg_bo2, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 3 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaS0 : intercept in selection equation -->

<!-- ```{r Reg_bs0, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 4 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaS1 : coefficient on endogenous variable X1 -->

<!-- ```{r Reg_bs1, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 5 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaS2 : coefficient on exogenous variable X2 -->

<!-- ```{r Reg_bs2, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 6 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

<!-- ### betaS3 : coefficient on exclusion restriction variable X3 -->

<!-- ```{r Reg_bs3, echo=FALSE, warning=FALSE, results='asis'} -->
<!-- i <- 7 -->
<!-- res0[[i]]$overall_tab -->
<!-- cat("\n") -->
<!-- ``` -->

## ANOVA & Interaction Plots

### betaO0 : intercept in outcome equation

```{r ANOVA_bo0, echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE, results='asis'}
resO0 <- f_anova(data=dfreg, parname="betaO0", trimpct=0.003)
savedir <- "/Users/xindieh/Documents/3_Academics/Projects/8_SelectionBias/simulation/simstudy/"

i <- 1
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 2
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 3
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 4
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 5
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 6
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 7
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]

i <- 8
main <- paste0("ANOVA : ", resO0$select_dist[i], " - ", resO0$outcome_dist[i], " Specification")
resO0$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
write.table(resO0$anova[[i]]$anova_table, file=paste0(savedir, main), sep=",")
cat("\n")
cat(report(resO0$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO0$plot_DS[[i]]
resO0$plot_DX[[i]]
resO0$plot_XS[[i]]
```

### betaO1 : coefficient on endogenous variable X1

```{r ANOVA_bo1, echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE, results='asis'}
resO1 <- f_anova(data=dfreg, parname="betaO1", trimpct=0.003) 
## Logit-Logit
i <- 1
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 2
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 3
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 4
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 5
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 6
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 7
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

i <- 8
main <- paste0("ANOVA : ", resO1$select_dist[i], " - ", resO1$outcome_dist[i], " Specification")
resO1$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO1$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO1$plot_DS[[i]]
resO1$plot_DX[[i]]
resO1$plot_XS[[i]]

```

### betaO2 : coefficient on exogenous variable X2

```{r ANOVA_bo2, echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE, results='asis'}
resO2 <- f_anova(data=dfreg, parname="betaO2", trimpct=0.003) 

i <- 1
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 2
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 3
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 4
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 5
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 6
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 7
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]

i <- 8
main <- paste0("ANOVA : ", resO2$select_dist[i], " - ", resO2$outcome_dist[i], " Specification")
resO2$anova[[i]]$anova_table %>% 
  kable(caption=main, digits=2, table.attr = "style='width:30%;'")
cat("\n")
cat(report(resO2$anova[[i]]$anova_table))
cat("\n\n##### Two-way Interaction Plots \n")
resO2$plot_DS[[i]]
resO2$plot_DX[[i]]
resO2$plot_XS[[i]]
```


### method wise

```{r ANOVA_method, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
savedir <- "/Users/xindieh/Documents/3_Academics/Projects/8_SelectionBias/simulation/simstudy/"
trimpct <- 0.003
parnames <- c("betaO0", "betaO1", "betaO2", "betaS0", "betaS1", "betaS2", "betaS3")

res_method <- data.frame()
for (par in parnames) {
  res_tmp <- f_method(data=dfreg[dfreg$method!="OLS",], parname=par, trimpct=trimpct)
  vheader <- cbind(res_tmp[,1:2], par)
  newcol <- res_tmp$anova %>% 
    lapply(FUN=function(x){return(data.frame(x$anova_table))}) %>% 
    Reduce(f=rbind, x=.)
  tmp <- cbind(vheader, newcol, row.names=NULL)
  res_method <- rbind(res_method, tmp)
}

kable(res_method %>% arrange(select_dist, outcome_dist, par), digits=2)
```

